### ISSUE TITLE
EPIC: Improve Cypress testing

### ISSUE THREAD

**Issue by AliceR** [NASA-IMPACT/admg-casei#33]
Every now and then the tests fail when running on CI, triggering them again will let them pass. This shouldn't happen, false alarms reduce our sensitivity for failing tests.

How can we make our tests more stable?
I need to learn more on [Best Practices](https://docs.cypress.io/guides/references/best-practices.html).

**Comment by LanesGood** [comment]
We've removed cypress from the project; now using [playwright](https://playwright.dev/) and [jest](https://jestjs.io/). See #457
