### ISSUE TITLE
Some campaign logos are missing

### ISSUE THREAD

**Issue by necoline** [NASA-IMPACT/admg-casei#348]
data issue, these campaigns don't have a logo with their api response:
"Aeolus Cal/Val", "logo": null,
"AfriSAR", "logo": null,
"CARAFE", "logo": null,
"CLASIC07", "logo": null,
"LMOS", "logo": null,
"LISTOS", "logo": null,
"OTTER", "logo": null,
"TEFLUN", "logo": null,
"VIRGAS", "logo": null,
"PODEX", "logo": null,
"ACTIVATE", "logo": null,
"Delta-X", "logo": null,
"DCOTSS", "logo": null,
"TC4", "logo": null,
"CITE", "logo": null,
"MACPEX", "logo": null,
"S-MODE", "logo": null,
"CPEX-AW", "logo": null,
"CASIE", "logo": null,
"POLARIS", "logo": null,
"CR-AVE", "logo": null,
"IMPACTS", "logo": null,
"TRACE", "logo": null,
"CRYSTAL-FACE", "logo": null,

**Comment by smwingo** [comment]
can we close this?  @heidimok @als0076 ?

**Comment by heidimok** [comment]
I added this as a nice-to-look-into from the backlog. I haven't had a chance to check on whether they are present or not. Maybe to close this sprint, I'll just move it back to the backlog and reassess before closing.

**Comment by heidimok** [comment]
Most of these have been resolved. Ill close this issue. There are a few that have missing logos but I think given this issue is quite old, and campaigns have been added since, we should report a new issue if we want to resolve additional ones.
