### ISSUE TITLE
[Flight tracks sprint 5] Visualize additional flight maps (for data gathered in sprint 4)

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-casei#595]
To visualize flight maps for data gathered in the previous sprint: https://docs.google.com/presentation/d/1rz0fjd7XhG6BzFwSlibW-OE8FJF7rlPvwIL73TRtLpQ/edit#slide=id.g2c2e0828ec7_0_2192

We can aim for 3-5.

**Comment by willemarcel** [comment]
@als0076 Could you take a look and tell me if the data looks good? If so, I can deploy it to production
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/VIRGAS
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/MACPEX
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/SEAC4RS

**Comment by als0076** [comment]
@willemarcel everything looks good to me

**Comment by heidimok** [comment]
I suggest we deploy these to production then :)

**Comment by willemarcel** [comment]
It's now deployed to production!

**Comment by willemarcel** [comment]
I've also updated OLYMPEX: https://impact.earthdata.nasa.gov/casei/campaign/OLYMPEX

It now has the Citation data, which was missing because previously we didn't support its file format.

**Comment by heidimok** [comment]
Closing as these flights have been deployed to production
