### ISSUE TITLE
Rename platform short names to be descriptive and easier to understand

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-casei#615]
## Scenario: 
Some platform names aren't meaningful or descriptive, and this makes the legend items unclear

## Solution: 
This is more of a curator goal to rename some of the platform short names, particularly stationary ones, to be more descriptive. 

<img width="587" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/58385e41-c603-4cdd-94f1-6dcb2c26c53d">

**Comment by smwingo** [comment]
BC, Ashlyn, Trang, Eli, et al:   Please let me know if any questions as you work on these.  note that "Campaign B" should be "Balloon Launch Sites"

**Comment by heidimok** [comment]
## Update for PI Planning 24.3

- **Question for curators:** To what extent have we been able to rename the stationary platforms? I just want to get a sense of where to fit this into sprint planning for the next PI

- **Note on development work after platforms are renamed** - Although updating names should update the filters on the CASEI website, it will not automatically update static location platform names on the flight maps. @willemarcel will still need to regenerate the GeoJSON files with the new names. This is a downside of not being able to automate the download process. However, it isn't too much effort and Wille has already started updating the [static location spreadsheet ](https://docs.google.com/spreadsheets/d/17v-ZfeWoPZoCAVSs57Y3Q1gKUe6S49fZ8rC2KOO_myY/edit) that @als0076 has been added to as new flights are added.

**Comment by als0076** [comment]
@heidimok the shortnames for the stationary platforms have been updated in the MI. I don't think they have been updated on the UI side of things yet. I added the names changes below:

Campaign B >> Balloon Launch Site
Campaign PL >> Permanent Land Site
Campaign FS >> Field Site
Campaign V >> Vehicle
Campaign PW >> Permanent Water Site
Campaign Ships >> Generic Vessel
Campaign S >> Field Survey

**Comment by heidimok** [comment]
Thanks @als0076 I'll look into the UI side. But we should be good then for @willemarcel to update the flight path legend.
