### ISSUE TITLE
[Sprint 2] Add 5-6 additional flight maps to CASEI

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-casei#619]
## Context
Back in FY24.1, we started visualizing flight paths for campaigns on CASEI. We started with 5 (see epic: https://github.com/NASA-IMPACT/admg-casei/issues/576) and have since expanded to ~8 (see YAML files https://drive.google.com/drive/u/0/folders/1R92_4YxYTo8oml0NHMCLFYJ-t-dHaWIR).

## Known Challenges
We learned through past efforts in trying to automate the data collection and visualization process that currently it is NOT possible to fully automate this process for these reasons:
  - **Inconsistent data formats as in NASA's case airborne data ownership is split across 12 DAACs** that all do things a bit differently
  - **Different ways to define measurement variable names.** This might not seem like a big deal but it really makes it hard/slow to get buy-in when building out features quickly as terminology is for queries and UI filters gets challenged back and forth. There are initiatives on streamlining language, for example the official [GCMD science keywords](https://wiki.earthdata.nasa.gov/display/CMR/GCMD+Keyword+Access) (which is a string of keywords) but each DAAC also has their own views and it’s an ongoing discussion.
  - **Incomplete data.** To get the full set of historical data to even visualize flights (let along instruments on each flight deployment), in many cases you’ll need to manually look for data that’s lock in PDFs still or old canned films for example that are not digitized. This is what the ADMG data curators have been doing and filling in for CASEI

## Goal
- We will continue to collect and visualize campaigns in batches (of around 5-6)
- We will incorporate fixes to common data issues along the way, and continue to learn about the extent to which we can still create a pipeline for visualizing nav data in the cloud without having to do it locally and save out GeoJSON files

## Acceptance Criteria
1. 5-6 additional nav data sets saved as YAML files https://drive.google.com/drive/u/0/folders/1R92_4YxYTo8oml0NHMCLFYJ-t-dHaWIR
2. Static locations for those campaigns https://docs.google.com/spreadsheets/d/17v-ZfeWoPZoCAVSs57Y3Q1gKUe6S49fZ8rC2KOO_myY/edit#gid=1924471089
3. 5-6  flight tracks visualized and deployed to CASEI

## Notes
- The repo used for this feature is https://github.com/NASA-IMPACT/casei-data-pipeline

**Comment by heidimok** [comment]
Future data collection request for @als0076 

As part of adding more visuals, Wille was not able to query the CMR using the info on this [spreadsheet](https://docs.google.com/spreadsheets/d/1RWYbaMlXr8T6aCrrVv99HLCo3yEsR50O6FyPvf8qQE4/edit?pli=1#gid=0), nor were there additional [YAML files added to the Google Drive](https://drive.google.com/drive/u/0/folders/1R92_4YxYTo8oml0NHMCLFYJ-t-dHaWIR) that we haven't completed. So we need some additional help sourcing more links to the CMR, like the ones we had in this [initial spreadsheet](https://docs.google.com/spreadsheets/d/14vleSOggRQFfyT_wgvCGGlVpkpwzGiKM-ZPYE7xFjkQ/edit#gid=1224749507) in order to access more campaign data.

**Comment by heidimok** [comment]
Quick update:
- @als0076 @willemarcel aligned on using this original Google sheet to keep track of any new data: https://docs.google.com/spreadsheets/d/14vleSOggRQFfyT_wgvCGGlVpkpwzGiKM-ZPYE7xFjkQ/edit#gid=0

**Comment by willemarcel** [comment]
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/CPEX-AW
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/CPEX-CV
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/CR-AVE
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/ATTREX
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/ACT-America
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/ASHOE

I've processed and deployed those campaigns to the staging website. @als0076 Let me know if the data looks correct, so I can deploy it to production.

**Comment by als0076** [comment]
@willemarcel they all look good!

**Comment by heidimok** [comment]
Closing as these have been deployed to production. Thanks @willemarcel @als0076 

- https://impact.earthdata.nasa.gov/casei/campaign/ASHOE
- https://impact.earthdata.nasa.gov/casei/campaign/ACT-America
- https://impact.earthdata.nasa.gov/casei/campaign/ATTREX
- https://impact.earthdata.nasa.gov/casei/campaign/CR-AVE
- https://impact.earthdata.nasa.gov/casei/campaign/CPEX-CV
- https://impact.earthdata.nasa.gov/casei/campaign/CPEX-AW
