### ISSUE TITLE
[Sprint 3] Add 5-6 additional flight maps to CASEI

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-casei#620]
This issue assumes we've completed https://github.com/NASA-IMPACT/admg-casei/issues/619

## Context
Back in FY24.1, we started visualizing flight paths for campaigns on CASEI. We started with 5 (see epic: https://github.com/NASA-IMPACT/admg-casei/issues/576) and have since expanded to ~8 (see YAML files https://drive.google.com/drive/u/0/folders/1R92_4YxYTo8oml0NHMCLFYJ-t-dHaWIR).

## Known Challenges
We learned through past efforts in trying to automate the data collection and visualization process that currently it is NOT possible to fully automate this process for these reasons:
  - **Inconsistent data formats as in NASA's case airborne data ownership is split across 12 DAACs** that all do things a bit differently
  - **Different ways to define measurement variable names.** This might not seem like a big deal but it really makes it hard/slow to get buy-in when building out features quickly as terminology is for queries and UI filters gets challenged back and forth. There are initiatives on streamlining language, for example the official [GCMD science keywords](https://wiki.earthdata.nasa.gov/display/CMR/GCMD+Keyword+Access) (which is a string of keywords) but each DAAC also has their own views and it’s an ongoing discussion.
  - **Incomplete data.** To get the full set of historical data to even visualize flights (let along instruments on each flight deployment), in many cases you’ll need to manually look for data that’s lock in PDFs still or old canned films for example that are not digitized. This is what the ADMG data curators have been doing and filling in for CASEI

## Goal
- We will continue to collect and visualize campaigns in batches (of around 5-6). 
- We will incorporate fixes to common data issues along the way, and continue to learn about the extent to which we can still create a pipeline for visualizing nav data in the cloud without having to do it locally and save out GeoJSON files

## Acceptance Criteria
1. 5-6 additional nav data sets saved as YAML files https://drive.google.com/drive/u/0/folders/1R92_4YxYTo8oml0NHMCLFYJ-t-dHaWIR
2. Static locations for those campaigns https://docs.google.com/spreadsheets/d/17v-ZfeWoPZoCAVSs57Y3Q1gKUe6S49fZ8rC2KOO_myY/edit#gid=1924471089
3. 5-6  flight tracks visualized and deployed to CASEI

**Comment by willemarcel** [comment]
ARCTAS campaign is now processed: http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/ARCTAS

**Comment by heidimok** [comment]
Ready in staging:

http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/LISTOS
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/LMOS
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/NAMMA

I'm closing this issue, but note that we have a block in deploying to production: [#621](https://github.com/NASA-IMPACT/admg-backend/issues/621)
