### ISSUE TITLE
[FY24.4 Sprint 1] Add 2 additional flight maps to CASEI

### ISSUE THREAD

**Issue by heidimok** [NASA-IMPACT/admg-casei#634]
## Context
Back in FY24.1, we started visualizing flight paths for campaigns on CASEI. We started with 5 (see epic: https://github.com/NASA-IMPACT/admg-casei/issues/576) and have since expanded to ~8 (see YAML files https://drive.google.com/drive/u/0/folders/1R92_4YxYTo8oml0NHMCLFYJ-t-dHaWIR).

<img width="941" alt="image" src="https://github.com/NASA-IMPACT/admg-casei/assets/10764915/cdf66138-b9df-4b2b-a097-f6dfb2b15c08">
Example of a flight map for a campaign 

As of FY24.3, we have published 27 campaign flight paths.

## Known Challenges
We learned through past efforts in trying to automate the data collection and visualization process that currently it is NOT possible to fully automate this process for these reasons:
  - **Inconsistent data formats as in NASA's case airborne data ownership is split across 12 DAACs** that all do things a bit differently
  - **Different ways to define measurement variable names.** This might not seem like a big deal but it really makes it hard/slow to get buy-in when building out features quickly as terminology is for queries and UI filters gets challenged back and forth. There are initiatives on streamlining language, for example the official [GCMD science keywords](https://wiki.earthdata.nasa.gov/display/CMR/GCMD+Keyword+Access) (which is a string of keywords) but each DAAC also has their own views and it’s an ongoing discussion.
  - **Incomplete data.** To get the full set of historical data to even visualize flights (let along instruments on each flight deployment), in many cases you’ll need to manually look for data that’s lock in PDFs still or old canned films for example that are not digitized. This is what the ADMG data curators have been doing and filling in for CASEI

## Goal
- We will continue to collect and visualize campaigns in batches (of around 3-6) because each campaign may need some manual data fixes. 
- We will incorporate fixes to common data issues along the way, and continue to learn about the extent to which we can still create a pipeline for visualizing nav data in the cloud without having to do it locally and save out GeoJSON files

## Acceptance Criteria
1. 2 additional nav data sets saved as YAML files https://drive.google.com/drive/u/0/folders/1R92_4YxYTo8oml0NHMCLFYJ-t-dHaWIR
2. Static locations for those campaigns https://docs.google.com/spreadsheets/d/17v-ZfeWoPZoCAVSs57Y3Q1gKUe6S49fZ8rC2KOO_myY/edit#gid=1924471089
3. 2 flight tracks visualized and deployed to CASEI in staging
4. Deploy from staging to production

**Comment by heidimok** [comment]
Future note for @LanesGood to move this issue out of backlog and label the correct PI Iteration and PI Sprint once the team has set up the project board for the next PI.

**Comment by LanesGood** [comment]
Updated to reflect conservative estimate of adding 5 flight paths in this PI - we'll add 2 paths in the first sprint, rather than 3-6.

**Comment by willemarcel** [comment]
@als0076 I've deployed 4 campaigns to staging, could you check if the data looks ok?

http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/IPHEx
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/FIREX-AQ
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/GCPEx
http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/DISCOVER-AQ (this one can take some time to load the map, as the geojson file is quite big)

**Comment by als0076** [comment]
@willemarcel still waiting on DISCOVER-AQ to load but the rest look ready to deploy to production

**Comment by als0076** [comment]
@willemarcel DISCOVER-AQ finally loaded and it looks good to go!

**Comment by willemarcel** [comment]
@als0076 We are having a problem deploying DISCOVER-AQ data, but now you can access it.

**Comment by smwingo** [comment]
@willemarcel -- i am having to move the map around first to see anything -- when i initially scroll down the page/see the box for where map should be it's only a black box, once i move it around/zoom  in or out, it shows up fine -- is this expected? 

Also:   Can we try to revisit the icons being used for the non-moving platforms?  Is there a bank you're pulling from and/or would it be helpful if i suggested some from a place like noun project??

**Comment by willemarcel** [comment]
@smwingo That problem is not expected, although I've noticed a few times that the map took a bit more long to load. @als0076 Have you experienced that problem too?

We got the icons from [Font Awesome](https://fontawesome.com/icons).

**Comment by als0076** [comment]
@willemarcel I did not have any issues with the maps loading

**Comment by smwingo** [comment]
Some alternate icons options:

Balloon Launch Site:
fine as it is now :)

Vehicle:
fine as it is now :)

Field Site:
[observation tower icon](https://fontawesome.com/icons/tower-observation?f=classic&s=thin)

Permanent Land Site:
[bold obs tower icon](https://fontawesome.com/icons/tower-observation?f=classic&s=regular)

**Comment by willemarcel** [comment]
@als0076 I've processed a new campaign: http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/ACCLIP

Could you check if the data looks correct?

**Comment by als0076** [comment]
@willemarcel ACCLIP looks correct

**Comment by willemarcel** [comment]
Thanks, @als0076! It's now deployed to production.

**Comment by LanesGood** [comment]
@willemarcel added 5 additional flight maps this sprint:
- ACCLIP
- IPHEx
- FIREX-AQ
- GCPEx
- DISCOVER-AQ
