### ISSUE TITLE
Add Banner/Link to workshop recordings to CASEI homepage

### ISSUE THREAD

**Issue by LanesGood** [NASA-IMPACT/admg-casei#641]

**Comment by smwingo** [comment]
Banner text to add:

"
July update:  Please note that session recordings from the 2024 Airborne & Field Data Workshop are now available [here](https://www.earthdata.nasa.gov/learn/webinars-and-tutorials/second-airborne-field-data-workshop)!  
"

Duration:  please have this banner show on the CASEI homepage until 6 August.
