### ISSUE TITLE
Updates to “Coming Soon” page

### ISSUE THREAD

**Issue by LanesGood** [NASA-IMPACT/admg-casei#642]
## Situation
- Users are not always able to access the Coming Soon page from all expected entry points.
- Information on Coming Soon page may not reflect accurate information

## Acceptance Criteria
- [ ] Ensure that in-progress results are included on the coming soon page
- [ ] Confirm coming soon links are shown from the Home search box, not just explore page

**Comment by smwingo** [comment]
Some notes I made when preping some CASEI demo material:

CSP:  if i type "tiger" in search box on home page, no result, not CSP.  

Seems CSP only is accessible from typed in search with no results on explore page (not home) -- should be able to get to it either way

**Comment by LanesGood** [comment]
The "Upcoming" page is only displayed when a user executes a search from the Explore page, and no results are returned.

I noticed the additional potential issues:
- It's not clear that the message for "no results" is in fact a link to a "Coming Soon" page
    - <img src="https://github.com/NASA-IMPACT/admg-casei/assets/12634024/24fa81bc-4c1c-4a60-b6df-7b5af9062fcf" width="350" />
- The Coming Soon page itself is bare of other details, and does not include the rest of the page components. This could lead to confusion if accidentally linked from another source
    - <img src="https://github.com/NASA-IMPACT/admg-casei/assets/12634024/2eadb1ba-f5bc-45f3-8edb-4dd423922c21" width="350" />

### Additional Suggested solutions
- [x] Include a link to "Coming Soon" from the footer
- [x] Add the rest of the page layout (Header, footer, hero?) to the Coming Soon page to more explicitly align it with the rest of the site
- [x] Add an explicit link in the "No Results" message, rather than linking the entire message

**Comment by LanesGood** [comment]
@smwingo in #652 we are making some stylistic changes from the comments I made above. These are optional, but I believe that they can provide users with a more consistent user flow when navigating through the site to see upcoming data.

## Problem Investigation + Context
When investigating the original comments and request further, I noted the following:

The home page "Typeahead input" box is not the same as the "Search input" from the Explore page. The two different boxes serve two different purposes.

On the home page, the Typeahead can more accurately be thought of as "navigation shortcut" to go directly to a campaign/platform/instrument. I think this is somewhat hinted at by the placeholder text "Enter a campaign..."

![image](https://github.com/NASA-IMPACT/admg-casei/assets/12634024/884b14b3-5dfd-4d8f-ab14-084e88af8480)

I think this is more observable when users enter search terms in this vs. the search box on the Explore page. In the homepage, if I enter a term and then hit my <kbd>Enter</kbd> key, nothing happens. I have to directly move my mouse or arrow keys down to the correct term, if it exists, and then click/hit enter again to go to that page. Conversely, on the Explore page hitting enter executes a search on the database with the filters applied (search is actually executed automatically, without needing to hit enter).

## Solutions
I believe that there are three possible solutions:
1. Modify the typeahead box to function like a search box; allowing users to type any text, and providing a link in the dropdown to the "Coming Soon" page if that text is not found. If this option is preferred, I would also recommend changing the text in this box to "**Search** for a campaign, platform or instrument"

    If we do change the typeahead box to permit users to navigate the Coming Soon page, we will also want to explore how this should be displayed. Some questions include:
    - Should the Coming Soon link be displayed only if a user enters a term which is not found in the database, or on any text input?
    - Should the Coming Soon link be displayed directly in the list like all current results, or should the box behavior be changed to execute a search on <kbd>Enter</kbd>?
    - Should the Coming Soon link be displayed like the current other items, or have its own unique presentation?

2. Change the typeahead box placeholder text and iconography to more explicitly make this a shortcut navigation item: replacing the magnifying glass icon with an arrow/link/page icon, and changing the text to "**Navigate** to a campaign, platform or instrument"

3. Add a Coming Soon link directly below the typeahead box so that users may be able to navigate directly there, whether or not they enter a term for a C/P/I under review. (Similar to the current message under the filters on the Explore page)

All options are completely feasible and valid. The first option requires some minor changes in the typeahead search functionality, while the second and third options are a lighter lift. 

Which option would you say best fits the needs of users browsing the platform?

**Comment by smwingo** [comment]
i think 2 is best for how these are set up -- the box on homepage was always intended as a quick navigation through the site for users who already know what they're after -- the icon of the magnifying glass does seem to construe this a bit and i think was the primary root of my own confusion. 

i don't hate the "enter" wording, but perhaps can have text here something like "know what you're looking for?" just on top of the typeahead box too, in addition to replacing the icon -- if that doesn't make the area too busy looking

**Comment by LanesGood** [comment]
@smwingo please see the proposed design below:
![image](https://github.com/user-attachments/assets/9f6b0fae-e3f6-4cb1-9ae7-563fdba6e113)

**Comment by smwingo** [comment]
this would be "fine" i'm sure...but i'm also wondering....and since you've got design expertise please redirect if this seems silly...what if "direct navigation" was more like "I want to learn more about..." and then they type the thing they already know they're looking for...hope that idea makes sence?  if not, i think the "direct navigation" would be fine too

big fan of the arrow vs the magnifier icon for sure!

**Comment by LanesGood** [comment]
@smwingo From a content voice perspective, the CASEI website and most other NASA platforms don't offer the user a first person voice. The tone set by "I want to learn more about..." and "know what you're looking for?" both seem out of place -- they are more conversational, intimate, and indecisive. I would suggest instead following the more authoritative content voice of the rest of the platform for consistency.

Perhaps some other guidepost terminology to explore could include:
- "Navigate directly"
- "Data shortcut"
- "Discover metadata"
- "Quick link"

One tricky thing to balance here is ensuring that users are still aware that the main search is on the "Explore" page. To avoid confusion and still maintain a consistent voice, I think placeholder text could be updated to read something like "Go directly to a campaign, instrument or platform," or some other combination of the words above.

**Comment by smwingo** [comment]
i like "Go directly to a campaign, platform, or instrument" and "Data shortcut" the best.
