### ISSUE TITLE
Add permission to the CASEI deployment AWS Key

### ISSUE THREAD

**Issue by willemarcel** [NASA-IMPACT/admg-casei#661]
During the production deploy process, we copy the flight paths geojson files from a S3 bucket managed by Development Seed to the bucket where the production website is hosted (see [code](https://github.com/NASA-IMPACT/admg-casei/blob/develop/.github/workflows/deploy-to-production.yml#L70)). There is a new campaign file that has more than 8 MB, and it requires additional permission to be able to copy the file (see [error in the deploy github action](https://github.com/NASA-IMPACT/admg-casei/actions/runs/9897303416/job/27341460380#step:9:29420)). We had the same issue in the staging deploy bucket (this one is managed by a DevSeed AWS account), and we solved it by adding the `s3:GetObjectTagging` permission to the AWS key we use in the deploy.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ListObjectsInBucket",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::admg-inventory-staging"
            ]
        },
        {
            "Sid": "AllObjectActions",
            "Effect": "Allow",
            "Action": [
                "s3:*Object",
                "s3:PutObjectAcl",
                "s3:GetObjectTagging"
            ],
            "Resource": [
                "arn:aws:s3:::admg-inventory-staging/*"
            ]
        }
    ]
}
```

cc: @smwingo

**Comment by EJwalker13** [comment]
Currently interfacing with Caden to look into and resolve this issue.

**Comment by willemarcel** [comment]
It's now solved. The permission could be added in our bucket.
