### ISSUE TITLE
Confirm coming soon page contents

### ISSUE THREAD

**Issue by LanesGood** [NASA-IMPACT/admg-casei#663]
The coming soon page should render content from the `/unpublished_drafts` API endpoint. Currently it appears that not every item at the endpoint is included on the page. Investigate and confirm page contents, and modify filters or requirements as needed.

**Comment by smwingo** [comment]
discuss more at Thur 22 Aug dev seed meeting

**Comment by LanesGood** [comment]
@willemarcel has confirmed that the coming soon page renders content from the [`/unpublished_drafts`](https://admgstaging.nasa-impact.net/api/unpublished_drafts) endpoint that meets the following criteria:
- `content_type` is a Campaign, Platform, or Instrument
- content is a new entry
- content `status` is `IN_ADMIN_REVIEW`

cc @smwingo @als0076 @EJwalker13

**Comment by LanesGood** [comment]
From @als0076 on slack:
> platforms or instruments that are in the curation process are already in CASEI, so they will just be update drafts so will never be on the coming soon page.

@smwingo suggests changing to:
> update drafts in review? and/or admin review?

This sounds like a proposed backend change to update the /unpublished_drafts endpoint to include **All** content that is in review and/or admin review, and not just new entries. Is this correct? If so we can explore what would be included with this change.

**Comment by LanesGood** [comment]
@smwingo @als0076 @EJwalker13 are there any needed changes to the `/unpublished_drafts` endpoint creation? I would suggest that the team take a look at each status filter in the Management Interface for campaigns, platforms, and instruments, in order to see what is desired to show on the "Coming Soon" page.

**Comment by als0076** [comment]
I would say for the unpublished drafts the coming soon page would need to show drafts that at least have a status of "Awaiting Review" and later. I think showing just drafts with a label of "In Progress" would not accurately display the drafts actively being worked on. @smwingo can correct me if I am wrong with this?

Update drafts should probably follow a similar process.

**Comment by smwingo** [comment]
yes ^^^ I agree w/ Ashlyn -- thought i think update drafts that are just "created" would actually be items that already have been (partly) curated and might already, technically, "be" in CASEI -- eg:  instruments that have very limited metadata and then later undergo full curation -- but this is fine, bc we'd want to show that the full updates are "coming soon"

so yes - as ashlyn described.

**Comment by smwingo** [comment]
Question:   will any drafts for things that have been "deleted" then show up?   bc we don't want those...

**Comment by smwingo** [comment]
need clarity to define this further. 

what items associated with each curation status

**Comment by smwingo** [comment]
Ashlyn + Lane to discuss.

**Comment by LanesGood** [comment]
Discussed with @als0076 and we've concluded that the following should be the status filters to compose the `unpublished_drafts` API response: `[Awaiting Review, In Review, Awaiting Admin Review, In Admin Review]`

We agreed that the "New entry" filter still made sense as the "update drafts" content will reflect items already discoverable on the CASEI platform; it would thus not make sense to include the names of those items on the "Coming Soon" page.

**Comment by smwingo** [comment]
closing as we're at end of PI -- and I believe this has been done/completed/pushed to prod :)
