### ISSUE TITLE
Explore rendering campaign flight paths on globe

### ISSUE THREAD

**Issue by LanesGood** [NASA-IMPACT/admg-casei#677]
Flight paths that cross or track near to the poles are incorrectly rendered in Mapbox/maplibre. We should consider using DeckGL to render flight paths on a globe view. (MapboxGL globe view is not adequate for high latitudes)

**Comment by smwingo** [comment]
my note on Slack from Fri:
> there was some discussion on the projections in sprint review -- the general suggestion was to see if any input from the IMPACT VEDA team might help as they've worked with a variety of projections ... i am not sure how/if that would fold in to the maps we already have, and i don't want to have to re-do the maps we've made...but i am not a developer... 

Wille continues to explore...

**Comment by LanesGood** [comment]
Completed in #691.
