### ISSUE TITLE
Automatically show flight map in 3D view for campaigns where flights cross poles

### ISSUE THREAD

**Issue by LanesGood** [NASA-IMPACT/admg-casei#699]
For campaigns with processed flight path data, automatically show map in 3D/globe mode (added in #691) when the flight path crosses arctic/antarctic circles.

**Comment by willemarcel** [comment]
@LanesGood I committed it directly to `develop` accidentally https://github.com/NASA-IMPACT/admg-casei/commit/321269f5e9f8cf41aebbf1e8786ea442c2c48319

Could you check if the implementation is good?

**Comment by LanesGood** [comment]
@willemarcel looks good! Campaigns I tested are ARCTAS (default 3D), ARISE (default 3D), OLYMPEX (default 2D) and many other default 2D maps.
