### ISSUE TITLE
Add icon for Rocket Launch Site

### ISSUE THREAD

**Issue by willemarcel** [NASA-IMPACT/admg-casei#704]
In the [SOLVE campaign](http://admg-inventory-staging.s3-website-us-east-1.amazonaws.com/casei/campaign/SOLVE/), we have `Rocket Launch Site` as one of the static platforms, so we need an icon for it.

**Comment by LanesGood** [comment]
Options:
[Rocket Light](https://fontawesome.com/icons/rocket?f=classic&s=light): ![image](https://github.com/user-attachments/assets/3d06017a-8249-4fdd-857c-f0c0de843c84)

[Rocket Launch Light:](https://fontawesome.com/icons/rocket-launch?f=classic&s=light) ![image](https://github.com/user-attachments/assets/e49f10ce-89e1-4038-99d9-ef36ecf04e45)

I recommend Rocket Light. @smwingo would you like to open this up for wider suggestions from the team, or would you endorse Rocket Light for the icon?

**Comment by smwingo** [comment]
"rocket light" is fine by me!
