### ISSUE TITLE
Incorrect GlobeView stationary platforms 

### ISSUE THREAD

**Issue by LanesGood** [NASA-IMPACT/admg-casei#709]
Campaign deployment flight maps shown in GlobeView are displaying some incorrect icons.

For example:
INTEX-NA 2D view:
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/6f980f65-a0cb-4e1f-8006-97ff9a7ae012">

INTEX-NA 3D view (rocket icon in place of vehicle):
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/d0d36c50-ee1e-46e1-9e31-821537d0a897">

IMPACTS 2D
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/da65cf89-d1a0-4943-b344-2c32500379b9">

IMPACTS 3D
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/0d7eef73-6061-444e-b2bf-2e0ec497ef17">

**Comment by willemarcel** [comment]
@LanesGood Is this solved with #706?

**Comment by LanesGood** [comment]
@willemarcel no, the issue is present in that branch as well

**Comment by willemarcel** [comment]
@LanesGood I've just tried the code on main and the icons are correct in both maps. Could you try that again?

Impacts in 3D:
![Image](https://github.com/user-attachments/assets/a3ce6341-ee33-4bb6-b808-4d8a6189359d)

**Comment by LanesGood** [comment]
I'm also no longer seeing the issue - perhaps this was fixed in #706, or was a caching issue - I cleared all caches and all icons appear to be correct.
